# Generated by Django 4.2.23 on 2025-09-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astrologer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=200)),
                ('experience_years', models.PositiveIntegerField()),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
