# Generated by Django 4.2.23 on 2025-09-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrologer',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='astrologer',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='astrologer',
            name='expertise',
            field=models.CharField(max_length=255),
        ),
    ]
